Repository CodingTrain/thecodingtrain.com, pull requests merged in 2022-10, with the labels that each got.

#612 Showcase Submission for 19-superellipse
  content/videos/challenges/19-superellipse/showcase/contribution-1664720793.jpeg
  content/videos/challenges/19-superellipse/showcase/contribution-1664720793.json
Labels: showcase

#616 Added my showcase for Bubble Sort!
  content/videos/challenges/114-bubble-sort-visualization/showcase/contribution16.JPG
  content/videos/challenges/114-bubble-sort-visualization/showcase/contribution16.json
Labels: hacktoberfest-accepted

#620 [WIP] Adding CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, hacktoberfest

#639 Added note about hacktoberfest in README
  README.md
Labels: hacktoberfest

#646 A Showcase for coding challange 124: flocking fire helicopters
  content/videos/challenges/124-flocking-simulation/showcase/contribution-1664967168.json
  content/videos/challenges/124-flocking-simulation/showcase/contribution-1664967168.png
Labels: showcase, hacktoberfest-accepted

#622 Showcase Submission for 173-snake-applesoft-basic
  content/videos/challenges/173-snake-applesoft-basic/showcase/contribution-1664976489.json
  content/videos/challenges/173-snake-applesoft-basic/showcase/contribution-1664976489.png
Labels: showcase

#625 Showcase Submission for 149-tic-tac-toe
  content/videos/challenges/149-tic-tac-toe/showcase/contribution-1664993902.json
  content/videos/challenges/149-tic-tac-toe/showcase/contribution-1664993902.png
Labels: showcase

#642 Adding related challenges
  content/videos/challenges/1-starfield/index.json
  content/videos/challenges/10-dfs-maze-generator/index.json
  content/videos/challenges/11-3d-terrain-generation-with-perlin-noise/index.json
  content/videos/challenges/125-fourier-series/index.json
  content/videos/challenges/133-time-tables-cardioid-visualization/index.json
  content/videos/challenges/153-interactive-drawing-with-sketchrnn/index.json
  content/videos/challenges/19-superellipse/index.json
  content/videos/challenges/2-menger-sponge/index.json
  content/videos/challenges/20-3d-cloth-simulation/index.json
  content/videos/challenges/23-2d-supershapes/index.json
  content/videos/challenges/24-perlin-noise-flow-field/index.json
  content/videos/challenges/25-spherical-geometry/index.json
  content/videos/challenges/26-3d-supershapes/index.json
  content/videos/challenges/28-metaballs/index.json
  content/videos/challenges/29-smart-rockets-in-p5js/index.json
  content/videos/challenges/3-snake-game/index.json
  content/videos/challenges/4-purple-rain/index.json
  content/videos/challenges/5-space-invaders/index.json
  content/videos/challenges/55-mathematical-rose-patterns/index.json
  content/videos/challenges/6-mitosis-simulation/index.json
  content/videos/challenges/90-dithering/index.json
  content/videos/challenges/c4-worley-noise/index.json
  content/videos/challenges/c5-marching-squares/index.json
Labels: hacktoberfest-accepted

#632 Showcase Submission for 67-pong
  content/videos/challenges/67-pong/showcase/contribution-1665085801.json
  content/videos/challenges/67-pong/showcase/contribution-1665085801.png
Labels: showcase

#634 Showcase Submission for 16-l-system-fractal-trees
  content/videos/challenges/16-l-system-fractal-trees/showcase/contribution-1665121693.jpg
  content/videos/challenges/16-l-system-fractal-trees/showcase/contribution-1665121693.json
Labels: showcase

#636 Adding 103-Fire-Effect
  content/videos/challenges/103-fire-effect/images/fire-effect.jpg
  content/videos/challenges/103-fire-effect/index.jpg
  content/videos/challenges/103-fire-effect/index.json
  content/videos/challenges/103-fire-effect/showcase/contribution1.jpg
  content/videos/challenges/103-fire-effect/showcase/contribution1.json
  content/videos/challenges/103-fire-effect/showcase/contribution2.jpg
  content/videos/challenges/103-fire-effect/showcase/contribution2.json
  content/videos/challenges/103-fire-effect/showcase/contribution3.jpg
  content/videos/challenges/103-fire-effect/showcase/contribution3.json
  content/videos/challenges/103-fire-effect/showcase/contribution4.json
Labels: challenge, hacktoberfest, hacktoberfest-accepted

#635 Adding 78 simple particle system
  content/videos/challenges/78-simple-particle-system/images/simple-particle-system.jpg
  content/videos/challenges/78-simple-particle-system/index.jpg
  content/videos/challenges/78-simple-particle-system/index.json
  content/videos/challenges/78-simple-particle-system/showcase/contribution1.jpg
  content/videos/challenges/78-simple-particle-system/showcase/contribution1.json
  content/videos/challenges/78-simple-particle-system/showcase/contribution10.jpg
  content/videos/challenges/78-simple-particle-system/showcase/contribution10.json
  content/videos/challenges/78-simple-particle-system/showcase/contribution11.json
  content/videos/challenges/78-simple-particle-system/showcase/contribution12.json
  content/videos/challenges/78-simple-particle-system/showcase/contribution2.jpg
  content/videos/challenges/78-simple-particle-system/showcase/contribution2.json
  content/videos/challenges/78-simple-particle-system/showcase/contribution3.jpg
  content/videos/challenges/78-simple-particle-system/showcase/contribution3.json
  content/videos/challenges/78-simple-particle-system/showcase/contribution4.jpg
  content/videos/challenges/78-simple-particle-system/showcase/contribution4.json
  content/videos/challenges/78-simple-particle-system/showcase/contribution5.jpg
  content/videos/challenges/78-simple-particle-system/showcase/contribution5.json
  content/videos/challenges/78-simple-particle-system/showcase/contribution6.jpg
  content/videos/challenges/78-simple-particle-system/showcase/contribution6.json
  content/videos/challenges/78-simple-particle-system/showcase/contribution7.json
  content/videos/challenges/78-simple-particle-system/showcase/contribution8.jpg
  content/videos/challenges/78-simple-particle-system/showcase/contribution8.json
  content/videos/challenges/78-simple-particle-system/showcase/contribution9.jpg
  content/videos/challenges/78-simple-particle-system/showcase/contribution9.json
Labels: challenge, hacktoberfest, hacktoberfest-accepted

#637 Showcase Submission for 51-a-pathfinding-algorithm
  content/videos/challenges/51-a-pathfinding-algorithm/showcase/contribution-1665156776.jpg
  content/videos/challenges/51-a-pathfinding-algorithm/showcase/contribution-1665156776.json
Labels: showcase

#645 Pixel perfect adjustment on ButtonPanel
  src/components/ButtonPanel.module.css
  src/components/GuideCard.module.css
  src/components/PagePanel.module.css
  src/components/challenges/VideoSection.module.css
  src/components/tracks/VideoSection.module.css
  src/styles/pages/index.module.css
Labels: hacktoberfest-accepted

#640 Adding 111-animated-sprites
  content/videos/challenges/111-animated-sprites/index.jpg
  content/videos/challenges/111-animated-sprites/index.json
  content/videos/challenges/111-animated-sprites/showcase/contribution1.json
  content/videos/challenges/111-animated-sprites/showcase/contribution2.jpg
  content/videos/challenges/111-animated-sprites/showcase/contribution2.json
  content/videos/challenges/111-animated-sprites/showcase/contribution3.jpg
  content/videos/challenges/111-animated-sprites/showcase/contribution3.json
  content/videos/challenges/111-animated-sprites/showcase/contribution4.jpg
  content/videos/challenges/111-animated-sprites/showcase/contribution4.json
Labels: challenge, hacktoberfest-accepted

#648 Adding 66-javascript-countdown-timer
  content/videos/challenges/66-javascript-countdown-timer/images/javascript-countdown-timer.jpg
  content/videos/challenges/66-javascript-countdown-timer/index.jpg
  content/videos/challenges/66-javascript-countdown-timer/index.json
  content/videos/challenges/66-javascript-countdown-timer/showcase/contribution1.json
  content/videos/challenges/66-javascript-countdown-timer/showcase/contribution2.jpg
  content/videos/challenges/66-javascript-countdown-timer/showcase/contribution2.json
Labels: hacktoberfest-accepted

#653 Showcase Submission for 18-3d-fractal-trees
  content/videos/challenges/18-3d-fractal-trees/showcase/contribution-1665505434.jpg
  content/videos/challenges/18-3d-fractal-trees/showcase/contribution-1665505434.json
Labels: showcase

#656 Showcase Submission for CC 167 Image to ASCII
  content/videos/challenges/166-image-to-ascii/showcase/contribution6.json
  content/videos/challenges/166-image-to-ascii/showcase/contribution6.png
Labels: showcase

#658 Added submission for Selection Sort Visualization
  content/videos/challenges/114-bubble-sort-visualization/showcase/contribution17.JPG
  content/videos/challenges/114-bubble-sort-visualization/showcase/contribution17.json
Labels: showcase, hacktoberfest-accepted

#654 Showcase Submission for 149-tic-tac-toe
  content/videos/challenges/149-tic-tac-toe/showcase/contribution-1665509183.PNG
  content/videos/challenges/149-tic-tac-toe/showcase/contribution-1665509183.json
Labels: showcase

#650 Showcase Submission for 173-snake-applesoft-basic
  content/videos/challenges/173-snake-applesoft-basic/showcase/contribution-1665444978.json
  content/videos/challenges/173-snake-applesoft-basic/showcase/contribution-1665444978.png
Labels: showcase

#655 Adding 136-perlin-noise-gif-loops
  content/videos/challenges/136-polar-noise-loops/images/perlin-noise-gif-loops.jpg
  content/videos/challenges/136-polar-noise-loops/images/polar-perlin-noise-loops.jpg
  content/videos/challenges/136-polar-noise-loops/index.jpg
  content/videos/challenges/136-polar-noise-loops/index.json
  content/videos/challenges/136-polar-noise-loops/showcase/contribution1.jpg
  content/videos/challenges/136-polar-noise-loops/showcase/contribution1.json
  content/videos/challenges/136-polar-noise-loops/showcase/contribution10.jpg
  content/videos/challenges/136-polar-noise-loops/showcase/contribution10.json
  content/videos/challenges/136-polar-noise-loops/showcase/contribution11.jpg
  content/videos/challenges/136-polar-noise-loops/showcase/contribution11.json
  content/videos/challenges/136-polar-noise-loops/showcase/contribution12.jpg
  content/videos/challenges/136-polar-noise-loops/showcase/contribution12.json
  content/videos/challenges/136-polar-noise-loops/showcase/contribution13.jpg
  content/videos/challenges/136-polar-noise-loops/showcase/contribution13.json
  content/videos/challenges/136-polar-noise-loops/showcase/contribution2.jpg
  content/videos/challenges/136-polar-noise-loops/showcase/contribution2.json
  content/videos/challenges/136-polar-noise-loops/showcase/contribution3.jpg
  content/videos/challenges/136-polar-noise-loops/showcase/contribution3.json
  content/videos/challenges/136-polar-noise-loops/showcase/contribution4.jpg
  content/videos/challenges/136-polar-noise-loops/showcase/contribution4.json
  content/videos/challenges/136-polar-noise-loops/showcase/contribution5.jpg
  content/videos/challenges/136-polar-noise-loops/showcase/contribution5.json
  content/videos/challenges/136-polar-noise-loops/showcase/contribution6.jpg
  content/videos/challenges/136-polar-noise-loops/showcase/contribution6.json
  content/videos/challenges/136-polar-noise-loops/showcase/contribution7.jpg
  content/videos/challenges/136-polar-noise-loops/showcase/contribution7.json
  content/videos/challenges/136-polar-noise-loops/showcase/contribution8.jpg
  content/videos/challenges/136-polar-noise-loops/showcase/contribution8.json
  content/videos/challenges/136-polar-noise-loops/showcase/contribution9.jpg
  content/videos/challenges/136-polar-noise-loops/showcase/contribution9.json
Labels: hacktoberfest-accepted

#664 Adding 60-butterfly-generator
  content/videos/challenges/60-butterfly-generator/index.jpg
  content/videos/challenges/60-butterfly-generator/index.json
  content/videos/challenges/60-butterfly-generator/showcase/contribution1.json
Labels: hacktoberfest-accepted

#672 Added Insertion Sort Visualization
  content/videos/challenges/114-bubble-sort-visualization/showcase/contribution18.JPG
  content/videos/challenges/114-bubble-sort-visualization/showcase/contribution18.json
  content/videos/challenges/114-bubble-sort-visualization/showcase/contribution19.JPG
  content/videos/challenges/114-bubble-sort-visualization/showcase/contribution19.json
Labels: showcase, hacktoberfest-accepted

#676 Adding 131-bouncing-DVD-logo
  content/videos/challenges/131-bouncing-dvd-logo/index.jpg
  content/videos/challenges/131-bouncing-dvd-logo/index.json
  content/videos/challenges/131-bouncing-dvd-logo/showcase/contribution1.jpg
  content/videos/challenges/131-bouncing-dvd-logo/showcase/contribution1.json
  content/videos/challenges/131-bouncing-dvd-logo/showcase/contribution2.jpg
  content/videos/challenges/131-bouncing-dvd-logo/showcase/contribution2.json
  content/videos/challenges/131-bouncing-dvd-logo/showcase/contribution3.jpg
  content/videos/challenges/131-bouncing-dvd-logo/showcase/contribution3.json
  content/videos/challenges/131-bouncing-dvd-logo/showcase/contribution4.jpg
  content/videos/challenges/131-bouncing-dvd-logo/showcase/contribution4.json
  content/videos/challenges/131-bouncing-dvd-logo/showcase/contribution5.jpg
  content/videos/challenges/131-bouncing-dvd-logo/showcase/contribution5.json
  content/videos/challenges/131-bouncing-dvd-logo/showcase/contribution6.jpg
  content/videos/challenges/131-bouncing-dvd-logo/showcase/contribution6.json
  content/videos/challenges/131-bouncing-dvd-logo/showcase/contribution7.jpg
  content/videos/challenges/131-bouncing-dvd-logo/showcase/contribution7.json
Labels: hacktoberfest-accepted

#675 Porting CC 47 Pixel Sorting in Processing
  content/videos/challenges/47-pixel-sorting-in-processing/images/pixel-sorted-sunflower.jpg
  content/videos/challenges/47-pixel-sorting-in-processing/index.jpg
  content/videos/challenges/47-pixel-sorting-in-processing/index.json
  content/videos/challenges/47-pixel-sorting-in-processing/showcase/contribution1.jpg
  content/videos/challenges/47-pixel-sorting-in-processing/showcase/contribution1.json
  content/videos/challenges/47-pixel-sorting-in-processing/showcase/contribution2.json
Labels: hacktoberfest-accepted

#681 Porting CC 143 Quicksort Visualization
  content/videos/challenges/143-quicksort/index.jpg
  content/videos/challenges/143-quicksort/index.json
  content/videos/challenges/143-quicksort/showcase/contribution1.jpg
  content/videos/challenges/143-quicksort/showcase/contribution1.json
  content/videos/challenges/143-quicksort/showcase/contribution10.json
  content/videos/challenges/143-quicksort/showcase/contribution10.png
  content/videos/challenges/143-quicksort/showcase/contribution2.json
  content/videos/challenges/143-quicksort/showcase/contribution2.png
  content/videos/challenges/143-quicksort/showcase/contribution3.json
  content/videos/challenges/143-quicksort/showcase/contribution3.png
  content/videos/challenges/143-quicksort/showcase/contribution4.json
  content/videos/challenges/143-quicksort/showcase/contribution4.png
  content/videos/challenges/143-quicksort/showcase/contribution5.json
  content/videos/challenges/143-quicksort/showcase/contribution5.png
  content/videos/challenges/143-quicksort/showcase/contribution7.json
  content/videos/challenges/143-quicksort/showcase/contribution7.png
  content/videos/challenges/143-quicksort/showcase/contribution8.json
  content/videos/challenges/143-quicksort/showcase/contribution8.png
  content/videos/challenges/143-quicksort/showcase/contribution9.json
  content/videos/challenges/143-quicksort/showcase/contribution9.png
Labels: hacktoberfest-accepted

#686 Porting CC 089 Langton's Ant
  content/videos/challenges/89-langtons-ant/images/langton-ant.png
  content/videos/challenges/89-langtons-ant/index.jpg
  content/videos/challenges/89-langtons-ant/index.json
  content/videos/challenges/89-langtons-ant/showcase/contribution1.json
  content/videos/challenges/89-langtons-ant/showcase/contribution1.png
  content/videos/challenges/89-langtons-ant/showcase/contribution2.json
  content/videos/challenges/89-langtons-ant/showcase/contribution2.png
  content/videos/challenges/89-langtons-ant/showcase/contribution3.json
  content/videos/challenges/89-langtons-ant/showcase/contribution3.png
  content/videos/challenges/89-langtons-ant/showcase/contribution4.json
  content/videos/challenges/89-langtons-ant/showcase/contribution4.png
  content/videos/challenges/89-langtons-ant/showcase/contribution5.jpg
  content/videos/challenges/89-langtons-ant/showcase/contribution5.json
Labels: hacktoberfest-accepted

#689 Porting CC 139 Calculating Digits of Pi With Collisions
  content/videos/challenges/139-calculating-digits-of-pi-with-collisions/index.jpg
  content/videos/challenges/139-calculating-digits-of-pi-with-collisions/index.json
  content/videos/challenges/139-calculating-digits-of-pi-with-collisions/showcase/contribution1.json
  content/videos/challenges/139-calculating-digits-of-pi-with-collisions/showcase/contribution1.png
  content/videos/challenges/139-calculating-digits-of-pi-with-collisions/showcase/contribution3.json
  content/videos/challenges/139-calculating-digits-of-pi-with-collisions/showcase/contribution3.png
  content/videos/challenges/139-calculating-digits-of-pi-with-collisions/showcase/contribution4.json
  content/videos/challenges/139-calculating-digits-of-pi-with-collisions/showcase/contribution4.png
  content/videos/challenges/139-calculating-digits-of-pi-with-collisions/showcase/contribution6.json
  content/videos/challenges/139-calculating-digits-of-pi-with-collisions/showcase/contribution6.png
  content/videos/challenges/139-calculating-digits-of-pi-with-collisions/showcase/contribution7.json
  content/videos/challenges/139-calculating-digits-of-pi-with-collisions/showcase/contribution7.png
Labels: hacktoberfest-accepted

#694 Porting CC 138 Angry Birds With Matter.js
  content/videos/challenges/138-angry-birds-with-matterjs/index.jpg
  content/videos/challenges/138-angry-birds-with-matterjs/index.json
  content/videos/challenges/138-angry-birds-with-matterjs/showcase/contribution1.json
  content/videos/challenges/138-angry-birds-with-matterjs/showcase/contribution1.png
  content/videos/challenges/138-angry-birds-with-matterjs/showcase/contribution2.json
  content/videos/challenges/138-angry-birds-with-matterjs/showcase/contribution2.png
  content/videos/challenges/138-angry-birds-with-matterjs/showcase/contribution3.json
  content/videos/challenges/138-angry-birds-with-matterjs/showcase/contribution4.json
  content/videos/challenges/138-angry-birds-with-matterjs/showcase/contribution4.png
  content/videos/challenges/138-angry-birds-with-matterjs/showcase/contribution5.json
  content/videos/challenges/138-angry-birds-with-matterjs/showcase/contribution5.png
Labels: hacktoberfest

#693 Porting CC 137 4D OpenSimplex Noise Loop
  content/videos/challenges/137-4d-opensimplex-noise-loop/images/open-simplex-loop.png
  content/videos/challenges/137-4d-opensimplex-noise-loop/index.jpg
  content/videos/challenges/137-4d-opensimplex-noise-loop/index.json
  content/videos/challenges/137-4d-opensimplex-noise-loop/showcase/contribution1.json
  content/videos/challenges/137-4d-opensimplex-noise-loop/showcase/contribution1.png
Labels: hacktoberfest-accepted

#697 Adding 109 visualizing 500 000 subscribers
  content/videos/challenges/109-visualizing-500000-subscribers/index.jpg
  content/videos/challenges/109-visualizing-500000-subscribers/index.json
  content/videos/challenges/109-visualizing-500000-subscribers/showcase/contribution1.jpg
  content/videos/challenges/109-visualizing-500000-subscribers/showcase/contribution1.json
  content/videos/challenges/109-visualizing-500000-subscribers/showcase/contribution2.jpg
  content/videos/challenges/109-visualizing-500000-subscribers/showcase/contribution2.json
  content/videos/challenges/109-visualizing-500000-subscribers/showcase/contribution3.jpg
  content/videos/challenges/109-visualizing-500000-subscribers/showcase/contribution3.json
  content/videos/challenges/109-visualizing-500000-subscribers/showcase/contribution4.jpg
  content/videos/challenges/109-visualizing-500000-subscribers/showcase/contribution4.json
Labels: hacktoberfest-accepted

#700 Showcase submission for for Julia Set
  content/videos/challenges/22-julia-set/showcase/contribution7.json
  content/videos/challenges/22-julia-set/showcase/contribution7.png
Labels: hacktoberfest-accepted

#701 Adding 58 3d earthquake data visualization
  content/videos/challenges/58-3d-earthquake-data-visualization/index.jpg
  content/videos/challenges/58-3d-earthquake-data-visualization/index.json
  content/videos/challenges/58-3d-earthquake-data-visualization/showcase/contribution1.json
  content/videos/challenges/58-3d-earthquake-data-visualization/showcase/contribution2.jpg
  content/videos/challenges/58-3d-earthquake-data-visualization/showcase/contribution2.json
Labels: hacktoberfest-accepted

#708 Adding CC 063 Texturing Cloth Simulation (Unikitty Flag)
  content/videos/challenges/63-texturing-cloth-simulation/images/unikitty-flag.jpg
  content/videos/challenges/63-texturing-cloth-simulation/index.jpg
  content/videos/challenges/63-texturing-cloth-simulation/index.json
  content/videos/challenges/63-texturing-cloth-simulation/showcase/contribution1.jpg
  content/videos/challenges/63-texturing-cloth-simulation/showcase/contribution1.json
  content/videos/challenges/63-texturing-cloth-simulation/showcase/contribution2.jpg
  content/videos/challenges/63-texturing-cloth-simulation/showcase/contribution2.json
  content/videos/challenges/63-texturing-cloth-simulation/showcase/contribution3.json
  content/videos/challenges/63-texturing-cloth-simulation/showcase/contribution3.png
  content/videos/challenges/63-texturing-cloth-simulation/showcase/contribution4.json
  content/videos/challenges/63-texturing-cloth-simulation/showcase/contribution4.png
Labels: hacktoberfest-accepted

#709 42 markov chain name generator
  content/videos/challenges/42-markov-chain-name-generator/images/markov-chain-name-generator.jpg
  content/videos/challenges/42-markov-chain-name-generator/images/markov-chain-text.jpg
  content/videos/challenges/42-markov-chain-name-generator/index.jpg
  content/videos/challenges/42-markov-chain-name-generator/index.json
  content/videos/challenges/42-markov-chain-name-generator/showcase/contribution1.json
  content/videos/challenges/42-markov-chain-name-generator/showcase/contribution2.jpg
  content/videos/challenges/42-markov-chain-name-generator/showcase/contribution2.json
Labels: hacktoberfest-accepted

#714 Adding 44 afinn 111 sentiment analysis
  content/videos/challenges/44-afinn-111-sentiment-analysis/index.jpg
  content/videos/challenges/44-afinn-111-sentiment-analysis/index.json
  content/videos/challenges/44-afinn-111-sentiment-analysis/showcase/contribution1.jpg
  content/videos/challenges/44-afinn-111-sentiment-analysis/showcase/contribution1.json
  content/videos/challenges/44-afinn-111-sentiment-analysis/showcase/contribution2.jpg
  content/videos/challenges/44-afinn-111-sentiment-analysis/showcase/contribution2.json
  content/videos/challenges/44-afinn-111-sentiment-analysis/showcase/contribution3.jpg
  content/videos/challenges/44-afinn-111-sentiment-analysis/showcase/contribution3.json
Labels: hacktoberfest-accepted

#712 Adding 32 agario
  content/videos/challenges/32-agario/index.jpg
  content/videos/challenges/32-agario/index.json
  content/videos/challenges/32-agario/showcase/contribution1.jpg
  content/videos/challenges/32-agario/showcase/contribution1.json
Labels: hacktoberfest-accepted

#713 Porting CC 043 Context Free Grammar Generator
  content/videos/challenges/43-context-free-grammar/images/context-free-grammar.png
  content/videos/challenges/43-context-free-grammar/index.json
  content/videos/challenges/43-context-free-grammar/index.png
Labels: hacktoberfest-accepted

#720 Adding 45 p5js firebase drawings
  content/videos/challenges/45-p5js-firebase-drawings/index.jpg
  content/videos/challenges/45-p5js-firebase-drawings/index.json
  content/videos/challenges/45-p5js-firebase-drawings/showcase/contribution1.jpg
  content/videos/challenges/45-p5js-firebase-drawings/showcase/contribution1.json
Labels: hacktoberfest-accepted

#723 Porting CC 110 Recaman's Sequence
  content/videos/challenges/110-recamans-sequence/images/recaman.png
  content/videos/challenges/110-recamans-sequence/index.json
  content/videos/challenges/110-recamans-sequence/index.png
  content/videos/challenges/110-recamans-sequence/showcase/contribution1.json
  content/videos/challenges/110-recamans-sequence/showcase/contribution1.png
  content/videos/challenges/110-recamans-sequence/showcase/contribution2.json
  content/videos/challenges/110-recamans-sequence/showcase/contribution2.png
  content/videos/challenges/110-recamans-sequence/showcase/contribution3.json
  content/videos/challenges/110-recamans-sequence/showcase/contribution3.png
  content/videos/challenges/110-recamans-sequence/showcase/contribution4.json
  content/videos/challenges/110-recamans-sequence/showcase/contribution4.png
  content/videos/challenges/110-recamans-sequence/showcase/contribution5.json
  content/videos/challenges/110-recamans-sequence/showcase/contribution5.png
Labels: hacktoberfest-accepted

#724 Adding 79 number guessing chatbot
  content/videos/challenges/79-number-guessing-chatbot/index.jpg
  content/videos/challenges/79-number-guessing-chatbot/index.json
  content/videos/challenges/79-number-guessing-chatbot/showcase/contribution1.jpg
  content/videos/challenges/79-number-guessing-chatbot/showcase/contribution1.json
  content/videos/challenges/79-number-guessing-chatbot/showcase/contribution2.jpg
  content/videos/challenges/79-number-guessing-chatbot/showcase/contribution2.json
  content/videos/challenges/79-number-guessing-chatbot/showcase/contribution3.jpg
  content/videos/challenges/79-number-guessing-chatbot/showcase/contribution3.json
Labels: hacktoberfest-accepted

#719 Fixed expired Discord channel invite link
  content/pages/about/index.json
  content/pages/faqs/cafe-car.json
  content/pages/faqs/find-help.json
  content/pages/faqs/livestream-notification.json
  content/pages/faqs/suggest-topic.json
  content/pages/guides/maintain-website-guide.md
  content/pages/guides/passenger-showcase-guide.md
  node-scripts/yt-description.js
  redirects.json
  src/components/Footer.js
Labels: hacktoberfest-accepted

#726 Showcase Submission for 113-4d-hypercube-aka-tesseract
  content/videos/challenges/113-4d-hypercube-aka-tesseract/showcase/contribution-1666731741.json
  content/videos/challenges/113-4d-hypercube-aka-tesseract/showcase/contribution-1666731741.png
Labels: showcase

#729 Adding CC 080 Voice Chatbot with p5.Speech
  content/videos/challenges/80-voice-chatbot-with-p5speech/index.json
  content/videos/challenges/80-voice-chatbot-with-p5speech/index.png
  content/videos/challenges/80-voice-chatbot-with-p5speech/showcase/contribution1.json
  content/videos/challenges/80-voice-chatbot-with-p5speech/showcase/contribution1.png
Labels: hacktoberfest-accepted
